#!/bin/bash -l
#SBATCH --job-name=intrachromosomal_distances
#SBATCH --output=X_Y.o%j
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=4000
#SBATCH --time=3-12:00:00
#SBATCH --partition=long7
#SBATCH --account=bscb02
#SBATCH --exclude=cbsubscb17


#5

####################################################################################
# QC: First half of the process to find contact distances. Input is the out.bam file from hicBuildMatrix
#
# The output file automatically generated by the cluster has information on the total number of HiC contacts
# to double-check the matrix QC report. It also gives the number of contacts across chromosome arms (2L-2R) and within arms.
#
# The other output files (distances.txt) are used with the R script "Contact_distance_finding.R"
#
# In general, these are simple awk commands based on counting numbers of contacts involving specific chromosomes.
####################################################################################



echo doubled X_Y_2 total is
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_2/X_Y_2_5kb_out.bam | wc -l
echo doubled X_Y_2 between arm is 
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_2/X_Y_2_5kb_out.bam | awk '$3 ~ /chr2/' | awk '$7 ~ /chr2/' | wc -l
echo plus
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_2/X_Y_2_5kb_out.bam | awk '$3 ~ /chr3/' | awk '$7 ~ /chr3/' | wc -l
echo plus
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_2/X_Y_2_5kb_out.bam | awk '$3 ~ /Y/' | awk '$7 ~ /Y/' | wc -l
echo doubled X_Y_2 intra chromosome is
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_2/X_Y_2_5kb_out.bam | awk '$7 ~ /=/' | awk '{print ($4-$8)}' | wc -l
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_2/X_Y_2_5kb_out.bam | awk '$7 ~ /=/' | awk '{print ($4-$8)}' > X_Y_2_distances.txt
echo
echo


echo doubled X_Y_3 total is
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_3/X_Y_3_5kb_out.bam | wc -l
echo doubled X_Y_3 between arm is 
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_3/X_Y_3_5kb_out.bam | awk '$3 ~ /chr2/' | awk '$7 ~ /chr2/' | wc -l
echo plus
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_3/X_Y_3_5kb_out.bam | awk '$3 ~ /chr3/' | awk '$7 ~ /chr3/' | wc -l
echo plus
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_3/X_Y_3_5kb_out.bam | awk '$3 ~ /Y/' | awk '$7 ~ /Y/' | wc -l
echo doubled X_Y_3 intra chromosome is
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_3/X_Y_3_5kb_out.bam | awk '$7 ~ /=/' | awk '{print ($4-$8)}' | wc -l
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_3/X_Y_3_5kb_out.bam | awk '$7 ~ /=/' | awk '{print ($4-$8)}' > X_Y_3_distances.txt
echo
echo


echo doubled X_Y_4 total is
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_4/X_Y_4_5kb_out.bam | wc -l
echo doubled X_Y_4 between arm is 
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_4/X_Y_4_5kb_out.bam | awk '$3 ~ /chr2/' | awk '$7 ~ /chr2/' | wc -l
echo plus
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_4/X_Y_4_5kb_out.bam | awk '$3 ~ /chr3/' | awk '$7 ~ /chr3/' | wc -l
echo plus
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_4/X_Y_4_5kb_out.bam | awk '$3 ~ /Y/' | awk '$7 ~ /Y/' | wc -l
echo doubled X_Y_4 intra chromosome is
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_4/X_Y_4_5kb_out.bam | awk '$7 ~ /=/' | awk '{print ($4-$8)}' | wc -l
samtools view /fs/cbsuclarkfs1/storage/mrm332/NextSeq_all_merged/contact_matrices/X_Y_4/X_Y_4_5kb_out.bam | awk '$7 ~ /=/' | awk '{print ($4-$8)}' > X_Y_4_distances.txt
echo
echo
